import {GET_CUCM_ROUTES} from "../../../../constants";
import dataLoader from "./dataLoader";

const config = {
  tableDataLoader: dataLoader,
  // filterDataLoader: fetchFilterList,
  tableDataUrl: GET_CUCM_ROUTES,
  filterDataUrl: '',
  showGlobalSearch: false,
  columns: [
    {
      accessor: 'np_pattern',
      title: 'np_pattern',
      minWidth: 200,
      maxWidth: 200,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'gateway',
      title: 'gateway',
      minWidth: 250,
      maxWidth: 250,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'np_description',
      title: 'np_description',
      minWidth: 250,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'np_usecallingpartynum',
      title: 'np_usecallingpartynum',
      minWidth: 100,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'np_callingtransform',
      title: 'np_callingtransform',
      minWidth: 200,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'np_callingprefix',
      title: 'np_callingprefix',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'np_discard',
      title: 'np_discard',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'np_calledtransform',
      title: 'np_calledtransform',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'np_prefixdigitsout',
      title: 'np_prefixdigitsout',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'routelist',
      title: 'routelist',
      minWidth: 250,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'description',
      title: 'description',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'modeldevice',
      title: 'modeldevice',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'routegroup',
      title: 'routegroup',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'rl_rg_callingpartytransformationmask',
      title: 'rl_rg_callingpartytransformationmask',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'rl_rg_callingpartyprefixdigits',
      title: 'rl_rg_callingpartyprefixdigits',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'rl_rg_discard',
      title: 'rl_rg_discard',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'rl_rg_prifixdigitout',
      title: 'rl_rg_prifixdigitout',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'rl_rg_calledpartytransformationmask',
      title: 'rl_rg_calledpartytransformationmask',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'h323_callerid',
      title: 'h323_callerid',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'inbound_calls_prefix_gw',
      title: 'inbound_calls_prefix_gw',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'ipaddress',
      title: 'ipaddress',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'port',
      title: 'port',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'gw',
      title: 'gw',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'num_to_gw',
      title: 'num_to_gw',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'target',
      title: 'target',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'peer',
      title: 'peer',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'type',
      title: 'type',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'priority',
      title: 'priority',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'destination_pattern',
      title: 'destination_pattern',
      minWidth: 250,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'translation_incoming',
      title: 'translation_incoming',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'translation_outgoing',
      title: 'translation_outgoing',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'incoming_called_number',
      title: 'incoming_called_number',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'prefix',
      title: 'prefix',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'no_digit_strip',
      title: 'no_digit_strip',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'forward_digits',
      title: 'forward_digits',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'protocol',
      title: 'protocol',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'trunk_group',
      title: 'trunk_group',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
    {
      accessor: 'shutdown',
      title: 'shutdown',
      minWidth: 150,
      maxWidth: 350,
      sortable: false,
      filterable: false,
    },
  ]
}

export default config